version: "3.8"

services:
  # Spring Boot 애플리케이션
  krocs-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: krocs-backend
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - krocs-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: krocs-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - krocs-redis-data:/data
    command: ["redis-server", "--appendonly", "yes", "--save", "60", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped
    networks:
      - krocs-network

volumes:
  krocs-redis-data:

networks:
  krocs-network:
    driver: bridge
