spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}?sslmode=require
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: false
auth:
  dev:
    bootstrap-token: test-token
    user:
      id: "1"
      name: Developer
      role: USER
      email: dev@krocs.local
  jackson:
    time-zone: Asia/Seoul
  servlet:
    encoding:
      enabled: true
      force: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha