spring:
  config:
    import: optional:file:./config/application-secret.yml

  datasource:
    url: ${database.url}
    username: ${database.user}
    password: ${database.password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    open-in-view: false

  sql:
    init:
      mode: never

  jackson:
    time-zone: Asia/Seoul
  
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: prod
    default-schema: public

server:
  port: 8080