spring:
  datasource:
    url: jdbc:h2:mem:krocs_test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
  jackson:
    time-zone: Asia/Seoul
  liquibase:
    enabled: false