spring:
  config:
    import: optional:file:./config/application-secret.yml
  jpa:
    hibernate:
      ddl-auto: none  # or validate, create, create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${database.url}
    username: ${database.user}
    password: ${database.password}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev
    default-schema: public

# H2 콘솔 비활성화 (PostgreSQL 사용 시)
# h2:
#   console:
#     enabled: true
#     path: /h2-console