name: Backend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        
    - name: Grant execute permission for gradlew
      run: chmod +x backend/gradlew
      
    - name: Run tests with coverage
      working-directory: ./backend
      run: ./gradlew test jacocoTestReport jacocoTestCoverageVerification
      
    - name: Build project
      working-directory: ./backend
      run: ./gradlew build
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: backend/build/reports/tests/
        retention-days: 7
        
    - name: Upload JaCoCo coverage reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: jacoco-reports
        path: backend/build/reports/jacoco/
        retention-days: 7
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: backend/build/libs/
        retention-days: 7 